### PR TITLE
Use proper minor mode keymap to handle M-s / M-j

### PR DESCRIPTION
**Pull request by purcell**
In connection with https://github.com/melpa/melpa/pull/5209

### CODE REVIEW

**Comment by purcell** [comment]
Also needs a space before "clj-lp" in the mode lighter.

**Comment by stardiviner** [comment]
I updated source with your suggestion. Because I don't know how to merge pull request with a modification. So I commit myself. Sorry for this.

**Comment by purcell** [comment]
I don't see the changes in `master` - did you forget to push?

**Comment by stardiviner** [comment]
@purcell Aha, you're right, I forgot to switch back to `master` branch to merge `develop` branch.

**Comment by stardiviner** [comment]
Because that defined keybindings is global, and I moved this to Org Mode contrib libraries now. So close this PR now.

**Pull request closed without merging**
